### PR TITLE
Added content on Homepage + About + Resources + Events sections

### PR DESCRIPTION
**Pull request by cecilaki**

### CODE REVIEW

**Comment by mintcanary** [comment]
@cecilaki mostly looks like it will be fine. Could you change these few things though?

 - We don't want any of those config changes in this repo, because it will break stuff
 - Let's leave the footer changes out for now, and I will look at this separately, now that I know we do not want to use the Open Knowledge footer
 - Are you sure you want to make the resources heading on the home page plural? It will only ever show one resource.

**Comment by cecilaki** [comment]
Sure @mintcanary , no problem for the config changes - Didn't really know how to handle that. 
Ok to look later at the footer then. 

--> *Are you sure you want to make the resources heading on the home page plural? It will only ever show one resource.* Yes it's important we feature one resource on the homepage. We definitely want to keep it that way.

**Comment by mintcanary** [comment]
OK, could you make those changes before I merge @cecilaki ?

**Comment by cecilaki** [comment]
@mintcanary I've made the changes in the config + footer. Is that ok to merge or there's something else missing?

**Comment by cecilaki** [comment]
@smth wasn't sure if you got the previous comment

**Comment by smth** [comment]
I did @cecilaki Sorry, just didn't find the time to reply. Could you remove the footer changes completely? I'm trying to avoid confusion with the `ok-footer` file name (and keep the changes somewhat modular).

**Pull request merged**
